.class public Lcom/here/android/mpa/mapping/customization/CustomizableVariables;
.super Ljava/lang/Object;
.source ""


# annotations
.annotation build Lcom/nokia/maps/annotation/HybridPlus;
.end annotation

.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$ZoneBorder;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$WorldMountains;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$WoodlandInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Woodland;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Water;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$UniversityCampusInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$UniversityCampus;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$TruckLine;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$TruckIcon;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$TransitAccess;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Transit;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$TMC;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Street;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$StateLabel;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$StateBoundaryDisputed;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$StateBoundary;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$StateAbbreviationLabel;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$SportsComplexInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$SportsComplex;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Sky;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$ShoppingComplexInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$ShoppingComplex;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Sea;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$SSAO;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Runway;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$RouteStyle;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$RoadSign;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$River;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$RemainingRangeEV;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$RailyardInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Railyard;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Railway;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Rail;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$PointOfInterest;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$PedestrianPoint;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$PedestrianAreaInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$PedestrianArea;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$ParkInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Park;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Panorama;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Ocean;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NeighborhoodInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Neighborhood;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NativeReservationInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NativeReservation;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NationalWildlifeRefuge;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NationalStateParkInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NationalStatePark;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NationalReserve;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NationalRecreationAreaInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NationalRecreationArea;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NationalParkInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NationalPark;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NationalMilitaryPark;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NationalHistoricParkInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NationalHistoricPark;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NationalGrasslandInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NationalGrassland;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NationalForestInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$NationalForest;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$MountainRangeInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$MountainPeakInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$MountainPeakHeight;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$MountainPeak;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$MotorwayJunctionSimplified;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$MinorCountryLabel;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$MilitaryBaseInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$MilitaryBase;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$MarkingLane;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$MarkingDivider;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$MajorCountryLabel;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$LineOfControl;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$LaneWidthM;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$LandCover;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Land;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Lake;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$IslandInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$IntermittentRiver;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$IndustrialComplexInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$IndustrialComplex;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$HospitalCampusInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$HospitalCampus;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$HarborAreaInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$HarborArea;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$GolfCourseInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$GolfCourse;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Fog;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Ferry;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$FarPlane;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$ExtrudedBuildings;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$ExitInfoSimplified;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$ExitInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$EnvironmentalZoneInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$EnvironmentalZoneBorder;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$EnvironmentalZone;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$ElevationMap;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$DirectionalLight3;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$DirectionalLight2;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$DirectionalLight1;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$CountrySideLabel;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$CountryBoundaryDisputed;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$CountryBoundary;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$ContinentLabel;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$CongestionZoneInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$CongestionZoneBorder;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$CongestionZone;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$CityCenter;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$CemeteryInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Cemetery;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$CanalWaterChannel;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$BuiltupBorder;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$BuiltupArea;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$BuildingOutline;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$BuildingInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$BuildingAddress;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Building1Outline;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Building1;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Building;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Billboard;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$BeachInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Beach;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$BayHarbour;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$AvoidBlockedRoute;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Area;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$AnimalParkInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$AnimalPark;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$AmusementParkInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$AmusementPark;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$AmbientLight;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$AllotmentInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$Allotment;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$AirportAreaInfo;,
        Lcom/here/android/mpa/mapping/customization/CustomizableVariables$AirportArea;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
